### ISSUE TITLE
Customize marker with color, transparency size?

### ISSUE THREAD

**Issue by ovizii** [simonv3/annotate#23]
Looks and feels nice, could do with some extra options to customize the size, transparency and color of the dots on the images though.

Just my 2cents. Thanks for making the app available!

**Comment by simonv3** [comment]
Hey @ovizii, thanks for the thoughts. 

I'm hesitant to go down the route of adding customization ability for the markers because I'm definitely in the field of minimizing configuration options and solving them through good defaults.

If you think the icons need to be changed somehow because they're not usable enough, I'll definitely listen to your arguments though :)

**Comment by ovizii** [comment]
Well, here are my 2 cents: 
- Imho the markers are a bit big. 

All my other suggestions are not as important to me as the size.
