### ISSUE TITLE
couldn't annotate immediately after uploading image

### ISSUE THREAD

**Issue by jadeqwang** [simonv3/annotate#8]
After uploading an image, I couldn't immediately annotate. (Clicks were not causing notes to appear.)

When I closed the grain and re-opened it, the problem fixed itself.

(However, while I was diagnosing it, I was wondering if I just couldn't figure out how to annotate.)

**Comment by simonv3** [comment]
Cool beans, I'll have a look. Just quickly - what OS / browser are you using? This is definitely a bug, not a feature. I think I'll also be creating some sort of "commenting" mode to toggle, or like suggested in another issue, a two step annotation procedure so that people can click on the image and something will pop up asking "do you want to create a comment".

**Comment by jadeqwang** [comment]
Chrome on Mac OS X Yosemite.

Yeah, a toggle would be pretty great. :)

**Comment by simonv3** [comment]
I think I've fixed this, I'll ping the dev-group thread when I have a new package.

The canvas that registered the clicking didn't resize on an image appearing (so it was 0x0). This is now triggered properly because of the toggle between the two actions.
